name: iphone
description: iphone UI representation for web showcase
version: 0.0.5
repository: https://github.com/Antoinegtir/iphone
homepage: https://flutter-seo.web.app
View/report issues: https://github.com/Antoinegtir/iphone/issues
contributing: https://github.com/Antoinegtir/iphone/blob/main/CONTRIBUTING.md
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/colors/